export enum PermissionCode {

  PROJECT_READ = "PROJECT_READ",
  PROJECT_CREATE = "PROJECT_CREATE",
  PROJECT_UPDATE = "PROJECT_UPDATE",
  PROJECT_DELETE = "PROJECT_DELETE",

  TASK_READ = "TASK_READ",
  TASK_CREATE = "TASK_CREATE",
  TASK_UPDATE = "TASK_UPDATE",
  TASK_DELETE = "TASK_DELETE",

  WORKFLOW_READ = "WORKFLOW_READ",
  WORKFLOW_UPDATE = "WORKFLOW_UPDATE",
  WORKFLOW_REVIEW = "WORKFLOW_REVIEW",

  MASTER_DATA_READ = "MASTER_DATA_READ",
  MASTER_DATA_UPDATE = "MASTER_DATA_UPDATE",

  USER_READ = "USER_READ",
  USER_CREATE = "USER_CREATE",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",

}